# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('subject', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
