# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('subject', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
