# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=150)),
                ('to_user', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('auth', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
