# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notify_data_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('auth', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
